### PR TITLE
updated README.md, PKGBUILD scripts

### PR DESCRIPTION
**Pull request by mmsaeed509**
### updated README.md

- Warning

Screenshot_2022-08-07-11-51-00_3840x1080

- Note

Screenshot_2022-08-07-11-51-09_3840x1080

### updated PKGBUILD scripts
- fixing copying files to the root directory (stop copying files to  / )
- fixing "post_install()", "post_remove()" scripts

### CODE REVIEW

**Comment by jayrfs** [comment]
Hi, Could you tell us the reason for this commit?

bfe4b1c36a1582e1e553e424e980ac2e554bec9f

**Review by jayrfs — COMMENTED** [review]
Hi, Could you tell us the reason for this commit?

bfe4b1c36a1582e1e553e424e980ac2e554bec9f

**Comment by jayrfs** [comment]
Thank you.

I think bfe4b1c36a1582e1e553e424e980ac2e554bec9f and b4c5368c06f55e2aeabdaf99cfec862e59fb4998 could've been squashed together into a single commit :)

**Comment by JafarAkhondali** [comment]
@mmsaeed509 Thanks for the PR. I've added you as collaborator so you can merge PRs as well.  
@jayrfs Thanks for the review.

Anyways please let's keep peer reviewing any PR before merge.

**Comment by mmsaeed509** [comment]
thanks for the invitation, I've accepted it
It's great to work with you!

**Pull request merged**
