### PR TITLE
updated turbo-fan.service in PKGBUILD

### PR DESCRIPTION
**Pull request by mmsaeed509**

### CODE REVIEW

**Comment by JafarAkhondali** [comment]
Hello. Can you modify the build somehow to rebuild `Predator-Sense-systemd-git-1.0-1-any.pkg.tar.zst` in builds instead storing it in the repo?

**Comment by mmsaeed509** [comment]
Do you mean store all versions?

**Comment by JafarAkhondali** [comment]
I'm not familiar with arch package build system, but storing a built version of repository doesn't look like a good practice to me.  
In other words, why do we have to keep a [~5mg](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/blob/main/PKGBUILD/Predator-Sense-systemd-git-1.0-1-any.pkg.tar.zst) file in the repo, when we have all the source code available?

**Comment by mmsaeed509** [comment]
OK
merge the pull request, then I'll remove the package and upload it to AUR Repository

**Comment by mmsaeed509** [comment]
I'll close this pull request, as I submitted the changes on my forked repo (removed pkg), then I'll create a new pull request

**Pull request closed without merging**
