### PR TITLE
Added fixes for LTS kernels

### PR DESCRIPTION
**Pull request by LarryTheMagicDragon**
I have made it so it will conditionally add definitions for missing functions on LTS kernels. I have tested this on my machine on the LTS kernel and normal kernel after reboots.

### CODE REVIEW

**Comment by yhanruzai** [comment]
That patch still did not fix building on LTS Kernels on my system, so far building in the kernel version 6.6 resulted in the same result as the main branch;

**Comment by LarryTheMagicDragon** [comment]
Well damn, I'll load up the LTS kernel later and fix it

**Comment by davidwkr** [comment]
Trying in Linux 6.6.63-2-cachyos-lts

``❯ sudo ./install.sh
LTS kernel detected
make -C /lib/modules/6.6.63-2-cachyos-lts/build M=/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module modules
make[1]: Entering directory '/usr/lib/modules/6.6.63-2-cachyos-lts/build'
  CC [M]  /home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o
/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: In function ‘acer_wmi_input_setup’:
/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:3221:49: error: passing argument 2 of ‘wmi_install_notify_handler’ from incompatible pointer type [-Wincompatible-pointer-types]
 3221 |                                                 acer_wmi_notify, NULL);
      |                                                 ^~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void (*)(union acpi_object *, void *)
In file included from ./include/linux/i2c.h:13,
                 from ./include/uapi/linux/fb.h:6,
                 from ./include/linux/fb.h:7,
                 from /home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:22:
./include/linux/acpi.h:415:60: note: expected ‘wmi_notify_handler’ {aka ‘void (*)(unsigned int,  void *)’} but argument is of type ‘void (*)(union acpi_object *, void *)’
  415 |                                         wmi_notify_handler handler, void *data);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: At top level:
/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:1993:20: warning: ‘WMID_gaming_get_u64’ defined but not used [-Wunused-function]
 1993 | static acpi_status WMID_gaming_get_u64(u64 *value, u32 cap)
      |                    ^~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o] Error 1
make[2]: *** [/usr/lib/modules/6.6.63-2-cachyos-lts/build/Makefile:1929: /home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.63-2-cachyos-lts/build'
make: *** [Makefile:18: default] Error 2
rmmod: ERROR: Module acer_wmi is not currently loaded
rmmod: ERROR: Module facer is not currently loaded
insmod: ERROR: could not insert module src/facer.ko: Unknown symbol in module
[ 2620.672404] facer: Unknown symbol platform_profile_notify (err -2)
[ 2620.672580] facer: Unknown symbol platform_profile_remove (err -2)
[ 2620.704079] zsh[44822]: segfault at 10 ip 00005dffaee96ad5 sp 00007ffffd39ddd0 error 4 in zsh[5dffaee12000+da000] likely on CPU 10 (core 20, socket 0)
[ 2620.704088] Code: 85 ed 74 08 85 f6 0f 84 c1 01 00 00 45 31 e4 89 c2 81 e2 ff ff bf ff 89 53 10 a9 00 00 00 01 75 0c 48 8b 43 20 89 ee 48 89 df <ff> 50 10 48 83 7b 30 00 74 1c 48 8b 7b 08 ff 15 a7 13 07 00 48 8b
[ 2626.589518] facer: Unknown symbol platform_profile_register (err -2)
[ 2626.589554] facer: Unknown symbol platform_profile_notify (err -2)
[ 2626.589600] facer: Unknown symbol platform_profile_remove (err -2)
[ 2642.437952] facer: Unknown symbol platform_profile_register (err -2)
[ 2642.438020] facer: Unknown symbol platform_profile_notify (err -2)
[ 2642.438112] facer: Unknown symbol platform_profile_remove (err -2)
[*] Done
`

`

**Comment by LarryTheMagicDragon** [comment]
@yhanruzai @davidwkr It should work now. Let me know if you have any issues

**Comment by davidwkr** [comment]
> @yhanruzai @davidwkr It should work now. Let me know if you have any issues

Yes! It works now!

**Comment by yhanruzai** [comment]
Late to the party as usual, but it seems to work just fine.

**Pull request merged**
