### PR TITLE
acer_wmi_notify should still support kernel version less than 6.12

### LINKED ISSUE #210: Installation problem
System Information
        Manufacturer: Acer
        Product Name: Predator PH18-71
        Version: V1.15
        Serial Number: NHQKSED0073100589C7600
        UUID: 24558df0-683a-4b4a-9b0f-c01850da9527
        Wake-up Type: Power Switch
--
Base Board Information
        Manufacturer: RPL
        Product Name: EQS_RTX
        Version: V1.15
        Serial Number: NBQKS110023100589C7600
        Asset Tag: Type2 - Board Asset Tag
        Features:

I get this when i try to install it as a module for with sudo ./install.sh

make -C /lib/modules/6.6.62-gentoo-dist/build M=/home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module modules
make[1]: Går till katalogen ”/usr/src/linux-6.6.62-gentoo-dist”
Makefile:2075: !!!! WARNING !!!!
Makefile:2076: This kernel was configured and installed by the package manager.
Makefile:2077: "make" should not be run manually here.
Makefile:2078: See also: https://wiki.gentoo.org/wiki/Project:Distribution_Kernel
Makefile:2079: See also: https://wiki.gentoo.org/wiki/Kernel/Configuration
Makefile:2080: !!!! WARNING !!!!
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2075: !!!! WARNING !!!!
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2076: This kernel was configured and installed by the package manager.
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2077: "make" should not be run manually here.
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2078: See also: https://wiki.gentoo.org/wiki/Project:Distribution_Kernel
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2079: See also: https://wiki.gentoo.org/wiki/Kernel/Configuration
/usr/src/linux-6.6.62-gentoo-dist/Makefile:2080: !!!! WARNING !!!!
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-pc-linux-gnu-gcc (Gentoo 13.3.1_p20241025 p1) 13.3.1 20241024
  You are using:           gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116
  CC [M]  /home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o
/home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: I funktion ”acer_wmi_input_setup”:
/home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:3205:49: fel: skickar argument 2 till ”wmi_install_notify_handler” från inkompatibel pekartyp [-Wincompatible-pointer-types]
 3205 |                                                 acer_wmi_notify, NULL);
      |                                                 ^~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void (*)(union acpi_object *, void *)
I filen inkluderad ifrån ./include/linux/i2c.h:13,
                   ifrån ./include/uapi/linux/fb.h:6,
                   ifrån ./include/linux/fb.h:7,
                   ifrån /home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:22:
./include/linux/acpi.h:415:60: anm: ”wmi_notify_handler” {även ”void (*)(unsigned int,  void *)”} förväntades men argumentet har typ ”void (*)(union acpi_object *, void *)”
  415 |                                         wmi_notify_handler handler, void *data);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: På toppnivå:
/home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:1977:20: varning: ”WMID_gaming_get_u64” är definierad men inte använd [-Wunused-function]
 1977 | static acpi_status WMID_gaming_get_u64(u64 *value, u32 cap)
      |                    ^~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o] Fel 1
make[2]: *** [/usr/src/linux-6.6.62-gentoo-dist/Makefile:1929: /home/chris/Projekt/acer-predator-turbo-and-rgb-keyboard-linux-module] Fel 2
make[1]: *** [Makefile:234: __sub-make] Fel 2
make[1]: Lämnar katalogen ”/usr/src/linux-6.6.62-gentoo-dist”
make: *** [Makefile:14: default] Fel 2
rmmod: ERROR: Module acer_wmi is not currently loaded
rmmod: ERROR: Module facer is not currently loaded
insmod: ERROR: could not load module src/facer.ko: No such file or directory
[ 1133.205479] input: Logitech G Pro Wireless Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C088.0026/input/input60
[ 1133.327668] logitech-hidpp-device 0003:046D:C088.0026: input,hidraw10: USB HID v1.11 Keyboard [Logitech G Pro Wireless Gaming Mouse] on usb-0000:00:14.0-3/input1
[ 1133.389177] logitech-hidpp-device 0003:046D:C088.0027: HID++ 4.2 device connected.
[ 1133.417699] logitech-hidpp-device 0003:046D:C088.0027: hiddev101,hidraw11: USB HID v1.11 Device [Logitech G Pro Wireless Gaming Mouse] on usb-0000:00:14.0-3/input2
[ 1133.555701] elogind-daemon[2281]: Watching system buttons on /dev/input/event26 (Logitech G Pro Wireless Gaming Mouse)
[ 1136.913436] usb usb1-port3: disabled by hub (EMI?), re-enabling...
[ 1136.913458] usb 1-3: USB disconnect, device number 15
[ 3980.789190] acer_wmi: Acer Laptop WMI Extras unloaded
[ 3980.887166] facer: version magic '6.4.14-gentoo-dist SMP preempt mod_unload ' should be '6.6.62-gentoo-dist SMP preempt mod_unload '
[ 4230.519254] facer: version magic '6.4.14-gentoo-dist SMP preempt mod_unload ' should be '6.6.62-gentoo-dist SMP preempt mod_unload '
[*] Done

### PR DESCRIPTION
**Pull request by HollowMan6**
Will need some review work (confirmation) from people using kernel version 6.12 as I'm not using it.

Related to #184

Fixes #210 

Error now when compiled in kernel version 6.11:

```log
./src/facer.c: In function ‘acer_wmi_input_setup’: ./src/facer.c:3205:49: error: passing argument 2 of ‘wmi_install_notify_handler’ from incompatible pointer type [-Wincompatible-pointer-types]
 3205 |                                                 acer_wmi_notify, NULL);
      |                                                 ^~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void (*)(union acpi_object *, void *)
In file included from ./include/linux/i2c.h:13,
                 from ./include/uapi/linux/fb.h:6,
                 from ./include/linux/fb.h:5,
                 from ./src/facer.c:22:
./include/linux/acpi.h:402:60: note: expected ‘wmi_notify_handler’ {aka ‘void (*)(unsigned int,  void *)’} but argument is of type ‘void (*)(union acpi_object *, void *)’
  402 |                                         wmi_notify_handler handler, void *data);
      |                                         ~~~~~~~~~~~~~~~~~~
```

cc: @LarryTheMagicDragon

### CODE REVIEW

**Comment by LarryTheMagicDragon** [comment]
Sorry I didn't realize that my changes would break older kernels. I read the documentation for the functions involved for the latest and 6.8. I thought that my changes would work on older versions.

**Comment by HollowMan6** [comment]
That's OK, this is a breaking change introduced by the kernel community, and we have to adapt the code for it sooner or later anyway. The source of the change is https://github.com/torvalds/linux/commit/e04e2b760ddbe3d7b283a05898c3a029085cd8cd. It looks like it's only applicable since 6.12.

**Comment by xAlpharax** [comment]
idk if this is related to my problem but now not even 6.12 works with it lol

alphara@deltarion ~/dev/acer-rgb-turbo> sudo /home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/purpleblue.sh 25 0 255 100

/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: In function 'acer_wmi_notify':
/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2942:18: error: implicit declaration of function 'wmi_get_event_data' [-Werror=implicit-function-declaration]
 2942 |         status = wmi_get_event_data(value, &response);
      |                  ^~~~~~~~~~~~~~~~~~
/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: In function 'acer_wmi_input_setup':
/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:3175:49: error: passing argument 2 of 'wmi_install_notify_handler' from incompatible pointer type [-Werror=incompatible-pointer-type
]
 3175 |                                                 acer_wmi_notify, NULL);
      |                                                 ^~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void (*)(u32,  void *) {aka void (*)(unsigned int,  void *)}
In file included from ./include/linux/i2c.h:13,
                 from ./include/uapi/linux/fb.h:6,
                 from ./include/linux/fb.h:5,
                 from /home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:19:
./include/linux/acpi.h:404:60: note: expected 'wmi_notify_handler' {aka 'void (*)(union acpi_object *, void *)'} but argument is of type 'void (*)(u32,  void *)' {aka 'void (*)(unsigned int,  void *)'}
  404 |                                         wmi_notify_handler handler, void *data);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: At top level:
/home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:1953:20: warning: 'WMID_gaming_get_u64' defined but not used [-Wunused-function]
 1953 | static acpi_status WMID_gaming_get_u64(u64 *value, u32 cap)
      |                    ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:229: /home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o] Error 1
make[2]: *** [/usr/src/kernel-headers-6.12.1_1/Makefile:1936: /home/alphara/dev/acer-predator-turbo-and-rgb-keyboard-linux-module] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make: *** [Makefile:14: default] Error 2
rmmod: ERROR: Module acer_wmi is not currently loaded
insmod: ERROR: could not insert module src/facer.ko: Invalid module format
alphara@deltarion ~/dev/acer-rgb-turbo>

**Comment by HollowMan6** [comment]
@xAlpharax Hmm, so you are compiling for 6.12.1, right? The error doesn't make sense as I can see, the error says that you are using the old function signature of `acer_wmi_notify` (with `u32`), but I already set it to use the new one if the Linux kernel version is equal to or higher to 6.12.0:

https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/pull/211/files#diff-28e326f1005bfd3ab7722ce793d0cd6bdafd7d5310ba2bc34331164d3d5ca5c1R2963-R2966

So would you please check your `LINUX_VERSION_CODE` under your compiling environment, I'm not sure if a mixup of header files causes it.

**Comment by xAlpharax** [comment]
> @xAlpharax Hmm, so you are compiling for 6.12.1, right? The error doesn't make sense as I can see, the error says that you are using the old function signature of `acer_wmi_notify` (with `u32`), but I already set it to use the new one if the Linux kernel version is equal to or higher to 6.12.0:
> 
> https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/pull/211/files#diff-28e326f1005bfd3ab7722ce793d0cd6bdafd7d5310ba2bc34331164d3d5ca5c1R2963-R2966
> 
> So would you please check your `LINUX_VERSION_CODE` under your compiling environment, I'm not sure if a mixup of header files causes it.

Sure, i can do that, I just check for that in m env vaiables?

**Comment by HollowMan6** [comment]
> Sure, i can do that, I just check for that in m env vaiables?

No, it's in the Linux header file which is included to compile your C program, for me it's under `/usr/include/linux/version.h`:

```c
#define LINUX_VERSION_CODE 396032
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
```

Not sure about your case, you might want to get the value printed somehow to confirm your header files are not mixed up.

**Comment by HollowMan6** [comment]
> my linux version code according to that is: 393472

`LINUX_VERSION_CODE` 393472 represents kernel version 6.1.0, which differs from what you are trying to compile for (6.12.1) and explains the error here. I'm not sure what went wrong with your system but that do suggest you mixed up the linux header files.

**Comment by xAlpharax** [comment]
> > my linux version code according to that is: 393472
> 
> `LINUX_VERSION_CODE` 393472 represents kernel version 6.1.0, which differs from what you are trying to compile for (6.12.1) and explains the error here. I'm not sure what went wrong with your system but that do suggest you mixed up the linux header files.

You re right! can t imagine why that had happened though, I ll try reinstalling the latest kernel update from my repos. Thanks

**Pull request merged**
